---
colors:
  - background: "#183036"
    text: "#f2d1ca"
  - background: "#a100c2"
    text: "#4dcb36"
  - background: "#2a54b3"
    text: "#e2ae4b"
  - background: "#a1ee66"
    text: "#5d0d9a"
  - background: "#ccebe5"
    text: "#361017"
  - background: "#b02c48"
    text: "#4ecbb3"
  - background: "#16530f"
    text: "#f4aff8"
  - background: "#2b0f7e"
    text: "#d9f581"
  - background: "#cfe883"
    text: "#2e147d"
  - background: "#cfeddb"
    text: "#29101f"
  - background: "#5e2424"
    text: "#a1e0de"
  - background: "#4a1d7a"
    text: "#b8e785"
  - background: "#212121"
    text: "#6e52df"
  - background: "#572217"
    text: "#a9e2ec"
  - background: "#140c0d"
    text: "#eaf9f7"
  - background: "#121480"
    text: "#fcef7f"
fonts:
  bold: fonts/NotoSansKR-Bold.otf
  light: fonts/NotoSansKR-Light.otf
  medium: fonts/NotoSansKR-Medium.otf
